### ISSUE TITLE
Deptrac binary fails on 'phar://box-auto’: No such file or directory

### ISSUE THREAD

**Issue by Mariyo** [sensiolabs-de/deptrac-shim#1]
Hello,
I wanted to run deptrac after few days and suddenly it started to fail with following error:

```
application@25b369e66727:/var/www/html$ vendor/bin/deptrac depfile.layers.yml 
/usr/bin/env: ‘php\r<?php\r\r/*\r * Generated by Humbug Box 3.8.4@120b0a3.\r *\r * @link https://github.com/humbug/box\r */\r\ruse const �\\C�3;use const �����1g\\eW;Phar::mapPhar('box-auto-generated-alias-21aa0e22f45f.phar');\r\rrequire 'phar://box-auto’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

I use the latest version: `"sensiolabs-de/deptrac-shim": "^0.7.1"`

Thank you for any help

**Comment by smoench** [comment]
Hi @Mariyo,
which operating system and php version are you using?

**Comment by Mariyo** [comment]
Hi @smoench ,
it runs on `Debian GNU/Linux 10 (buster)` and PHP version `7.4.6`

**Comment by smoench** [comment]
Is the phar extension enabled?

**Comment by Mariyo** [comment]
Yes, it is

**Comment by smoench** [comment]
@Mariyo Unfortunately I can't reproduce it :(

@theofidry Have you faced such issue with box once?

**Comment by smoench** [comment]
@Mariyo Does an earlier version or latest master (https://github.com/sensiolabs-de/deptrac/actions/runs/137633478 see build artifacts) works for you?

**Comment by Mariyo** [comment]
I neither can reproduce it. It somehow happens time to time, but has not appear since the issue reported, so lets close this issue till I can find way how to reproduce problem.

**Comment by sspat** [comment]
Got the same error today
`PHP 7.4.12 (cli) (built: Nov 18 2020 09:28:14) ( NTS )`
`Linux fa6ef8bc77e9 4.19.121-linuxkit #1 SMP Thu Jan 21 15:36:34 UTC 2021 x86_64 GNU/Linux`
`qossmic/deptrac-shim: 0.12.0`
```
Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Phar-based phar archives => enabled
Tar-based phar archives => enabled
ZIP-based phar archives => enabled
phar.cache_list => no value => no value
phar.readonly => On => On
phar.require_hash => On => On
```
```
> vendor/bin/deptrac analyze --fail-on-uncovered --report-uncovered
PHP Warning:  Phar::mapPhar(/app/vendor/bin/deptrac(21) : eval()'d code): failed to open stream: No such file or directory in /app/vendor/bin/deptrac(21) : eval()'d code on line 9

Warning: Phar::mapPhar(/app/vendor/bin/deptrac(21) : eval()'d code): failed to open stream: No such file or directory in /app/vendor/bin/deptrac(21) : eval()'d code on line 9
PHP Fatal error:  Uncaught PharException: unable to open phar for reading "/app/vendor/bin/deptrac(21) : eval()'d code" in /app/vendor/bin/deptrac(21) : eval()'d code:9
Stack trace:
#0 /app/vendor/bin/deptrac(21) : eval()'d code(9): Phar::mapPhar('box-auto-genera...')
#1 /app/vendor/bin/deptrac(21): eval()
#2 {main}
  thrown in /app/vendor/bin/deptrac(21) : eval()'d code on line 9

Fatal error: Uncaught PharException: unable to open phar for reading "/app/vendor/bin/deptrac(21) : eval()'d code" in /app/vendor/bin/deptrac(21) : eval()'d code:9
Stack trace:
#0 /app/vendor/bin/deptrac(21) : eval()'d code(9): Phar::mapPhar('box-auto-genera...')
#1 /app/vendor/bin/deptrac(21): eval()
#2 {main}
  thrown in /app/vendor/bin/deptrac(21) : eval()'d code on line 9
```

**Comment by sspat** [comment]
Same result when running on php8 or in Windows

**Comment by sspat** [comment]
Seems like this is not an issue of this package, as I started getting errors with other analysis tools.
When installing dependencies with any composer version higher than 2.0.9 I got these errors.
When installing dependencies with composer version 2.0.9 or lower, everything works fine.
So seems like a composer issue introduced in 2.0.10

**Comment by smoench** [comment]
@sspat It is related to https://github.com/composer/composer/issues/9742

**Comment by sspat** [comment]
Thank you, now it's clear! Sorry for bothering this issue)
