### ISSUE TITLE
Analyse does not generate graphical diagrams

### ISSUE THREAD

**Issue by Mariyo** [sensiolabs-de/deptrac-shim#2]
Hello,

I use version `0.8` of `deptrac-shim`, and decided tu add `graphviz` dependency. When I analyse my rules, no graphical diagrams are generated. I use command:
```
vendor/bin/deptrac analyse depfile.classes.yml
```

When I try `dot` in container, it generates diagram png. I use command:
```
application@4684f70391ed:/var/www/html$ echo "digraph G {Hello->World}" | dot -Tpng >hello.png
```

Any idea what's wrong?

**Comment by smoench** [comment]
Hi @Mariyo,
you need to enable the graphviz formatter with ` --formatter-graphviz=1`.
Try the following command:
```
vendor/bin/deptrac analyse --formatter-graphviz=1 depfile.classes.yml
```
There are more options available, you'll find them with `vendor/bin/deptrac --help`

**Comment by Mariyo** [comment]
Hi @smoench,

I have already tried `--formatter-graphviz=true` and now with `--formatter-graphviz=1`, but without luck.

**Comment by smoench** [comment]
Try following to dump an image:
```bash
vendor/bin/deptrac analyse --formatter-graphviz=1 --formatter-graphviz-display=0 --formatter-graphviz-dump-image=hello.png depfile.classes.yml
```

**Comment by Mariyo** [comment]
Yes, this is how it should be used,

Thank you
